/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

module rca_4bit(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [3:0] sum;
  wire [3:0] sum;
  sky130_fd_sc_hd__nand2_2 _17_ (
    .A(b[0]),
    .B(cin),
    .Y(_00_)
  );
  sky130_fd_sc_hd__or2_2 _18_ (
    .A(b[0]),
    .B(cin),
    .X(_01_)
  );
  sky130_fd_sc_hd__nand2_2 _19_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__xnor2_2 _20_ (
    .A(a[0]),
    .B(_02_),
    .Y(sum[0])
  );
  sky130_fd_sc_hd__o21ai_2 _21_ (
    .A1(b[0]),
    .A2(cin),
    .B1(a[0]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand2_2 _22_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__or2_2 _23_ (
    .A(b[1]),
    .B(a[1]),
    .X(_05_)
  );
  sky130_fd_sc_hd__a22o_2 _24_ (
    .A1(_00_),
    .A2(_03_),
    .B1(_04_),
    .B2(_05_),
    .X(_06_)
  );
  sky130_fd_sc_hd__nand4_2 _25_ (
    .A(_00_),
    .B(_03_),
    .C(_04_),
    .D(_05_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand2_2 _26_ (
    .A(_06_),
    .B(_07_),
    .Y(sum[1])
  );
  sky130_fd_sc_hd__nor2_2 _27_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a31o_2 _28_ (
    .A1(_00_),
    .A2(_03_),
    .A3(_04_),
    .B1(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__nand2_2 _29_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__or2_2 _30_ (
    .A(b[2]),
    .B(a[2]),
    .X(_11_)
  );
  sky130_fd_sc_hd__nand2_2 _31_ (
    .A(_10_),
    .B(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xor2_2 _32_ (
    .A(_09_),
    .B(_12_),
    .X(sum[2])
  );
  sky130_fd_sc_hd__and2_2 _33_ (
    .A(b[3]),
    .B(a[3]),
    .X(_13_)
  );
  sky130_fd_sc_hd__or2_2 _34_ (
    .A(b[3]),
    .B(a[3]),
    .X(_14_)
  );
  sky130_fd_sc_hd__or2b_2 _35_ (
    .A(_13_),
    .B_N(_14_),
    .X(_15_)
  );
  sky130_fd_sc_hd__a21boi_2 _36_ (
    .A1(_09_),
    .A2(_10_),
    .B1_N(_11_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__xnor2_2 _37_ (
    .A(_15_),
    .B(_16_),
    .Y(sum[3])
  );
  sky130_fd_sc_hd__o21a_2 _38_ (
    .A1(_13_),
    .A2(_16_),
    .B1(_14_),
    .X(cout)
  );
endmodule
